name: Solucao Estudo de Caso

on:
  push:
    branches:
      - main

jobs:
  usuarios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validar usuarios
        run: |
          test -f service-usuarios/index.html
          echo "Servico de usuarios validado"

  catalogo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validar catalogo
        run: |
          test -f service-catalogo/index.html
          echo "Servico de catalogo validado"

