name: Pipeline Cloud Native Simples

on:
  push:
    branches:
      - main

jobs:

  usuarios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validar Usuarios
        run: |
          echo "Servico de usuarios validado"

      - name: Simular Empacotamento
        run: |
          echo "Gerando pacote do servico de usuarios"

  catalogo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validar Catalogo
        run: |
          echo "Servico de catalogo validado"

      - name: Simular Empacotamento
        run: |
          echo "Gerando pacote do servico de catalogo"
